spring.application.name=temperatureAI
# Open-Meteo Configuration (No Key Needed!)
weather.api.base-url=https://api.open-meteo.com/v1/forecast
weather.geocoding-url=https://geocoding-api.open-meteo.com/v1/search
# --- GROQ FOR CHAT ---
# Use the 'chat' specific prefix to isolate Groq
spring.ai.openai.api-key=${Key}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile